# docker compose -f compose.simulation.yaml up
x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rosbot:
    image: husarion/rosbot-gazebo:humble-add-simulation-and-demo
    <<: [ *net-config, *gpu-config]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    command: ros2 launch rosbot_gazebo simulation.launch.py mecanum:=${MECANUM:-False}

  agent:
    image: microros/micro-ros-agent:humble
    <<: [ *net-config]
    restart: unless-stopped
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
    # volumes:
    # - ./fastdds.xml://tmp/disable_fastdds_shm.xml
    # devices:
    # - /dev/ttyUSB0
    command: tcp6 --port 6666 # -v6
    # command: serial -D /dev/ttyUSB0 serial -b 576000 -v6
